### PR TITLE
Platform::from_target_triplet

### PR DESCRIPTION
**Pull request by youknowone**

### CODE REVIEW

**Review by indygreg — APPROVED** [review]
This seems like a useful API. Thank you for adding it! Will merge this shortly.

**Comment by indygreg** [comment]
I'm going to make a minor tweak to change this to `from_target_triple()` because that is the terminology that Rust itself uses. I know `triplet` is often used interchangeably and this change is rather pedantic. But I feel like that is the slightly better name to use.

**Comment by youknowone** [comment]
Could you please also publish a new version of apple-sdk? I want to use this feature for other library but adding version dependency will be nice rather than adding git dependency 😄

**Comment by indygreg** [comment]
I can sympathize with not wanting to use Git dependencies! I just published version 0.2.0 on crates.io.

**Comment by youknowone** [comment]
Thank you!

**Pull request closed without merging**
